=== franzmelchiori/pat_pnrr/pat_pnrr_ssu/moduli_pat/02_entities/ent_pat_edilizia_persona_v1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:ccodelist="../commons/codelist"
    xmlns:cdichiara="../commons/dichiarazioni"
    xmlns:ctipi="../commons/tipi"
    xmlns:canncl="../commons/xsdAnnotations"
    xmlns:vpepergen="../01_vocabularies/persona_genere"
    xmlns:epepers="../02_entities/persona"
    targetNamespace="../02_entities/persona"
    elementFormDefault="qualified"
    attributeFormDefault="qualified"
    version="1.0.0"
    xml:lang="it">

    <xsd:import namespace="../commons/codelist" schemaLocation="../commons-codelist.xsd"/>
    <xsd:import namespace="../commons/dichiarazioni" schemaLocation="../commons-dichiarazioni.xsd"/>
    <xsd:import namespace="../commons/tipi" schemaLocation="../commons-tipi.xsd"/>
    <xsd:import namespace="../commons/xsdAnnotations" schemaLocation="../commons-xsd-annotations.xsd"/>
    <xsd:import namespace="../01_vocabularies/persona_genere" schemaLocation="../01_vocabularies/voc_pat_edilizia_persona_genere_v1.0.0.xsd"/>

    <xsd:complexType name="ent_pat_edilizia_persona_ctype">
        <xsd:sequence>
            <xsd:element name="nome" type="ctipi:stringa_standard_stype" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="cognome" type="ctipi:stringa_standard_stype" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="codiceFiscale" type="ctipi:codice_fiscale_stype" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="sesso" type="vpepergen:sesso_voc" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="dataNascita" type="ctipi:ggmmaaaa_stype"/>
            <xsd:element name="comuneNascita" type="ccodelist:CodeType" minOccurs="1" maxOccurs="1" >                
                <xsd:annotation>
                    <xsd:appinfo>                        
                        <canncl:codeListReference>
                            <canncl:ShortName>IT:SUAP:CL:ComuniItaliani</canncl:ShortName>
                        </canncl:codeListReference>                        
                    </xsd:appinfo>                    
                </xsd:annotation>                 
            </xsd:element>
            <xsd:element name="provinciaNascita" type="ccodelist:CodeType" minOccurs="1" maxOccurs="1" >                
                <xsd:annotation>
                    <xsd:appinfo>                        
                        <canncl:codeListReference>
                            <canncl:ShortName>IT:SUAP:CL:ProvinceItaliane</canncl:ShortName>
                        </canncl:codeListReference>                        
                    </xsd:appinfo>                    
                </xsd:annotation>                 
            </xsd:element>
            <xsd:element name="statoNascita" type="ccodelist:CodeType" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                    <xsd:appinfo>                        
                        <canncl:codeListReference>
                            <canncl:ShortName>IT:SUAP:CL:Stati</canncl:ShortName>                            
                        </canncl:codeListReference>                        
                    </xsd:appinfo>
                </xsd:annotation>                  
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="entita_pat_edilizia_persona" type="epepers:ent_pat_edilizia_persona_ctype"/>
</xsd:schema>

=== franzmelchiori/pat_pnrr/pat_pnrr_ssu/moduli_pat/02_entities/ent_pat_edilizia_persona_v1.0.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<epepers:entita_pat_edilizia_persona
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="../02_entities/ent_pat_edilizia_persona_v1.0.0.xsd"
    xmlns:ccodelist="../commons/codelist"
    xmlns:cdichiara="../commons/dichiarazioni"
    xmlns:ctipi="../commons/tipi"
    xmlns:canncl="../commons/xsdAnnotations"
    xmlns:epepers="../02_entities/persona">
    
    <epepers:nome>Mario</epepers:nome>
    <epepers:cognome>Rossi</epepers:cognome>
    <epepers:codiceFiscale>RSSMRA80A01H294E</epepers:codiceFiscale>
    <epepers:sesso>M</epepers:sesso>
    <epepers:dataNascita>01/01/1980</epepers:dataNascita>
    <epepers:comuneNascita>TN</epepers:comuneNascita>
    <epepers:provinciaNascita>TN</epepers:provinciaNascita>
    <epepers:statoNascita>IT</epepers:statoNascita>
</epepers:entita_pat_edilizia_persona>
